version: 0.2


phases:
  pre_build:
    commands:
      - mvn clean install
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region us-west-1 | docker login --username AWS --password-stdin 495642364690.dkr.ecr.us-west-1.amazonaws.com
      - REPOSITORY_URI=495642364690.dkr.ecr.us-west-1.amazonaws.com/grigor99
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t grigor99 .
      - docker tag grigor99:latest 495642364690.dkr.ecr.us-west-1.amazonaws.com/grigor99:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push 495642364690.dkr.ecr.us-west-1.amazonaws.com/grigor99:latest
      - echo Writing image definitions file...
      - printf '[{"name":"deploy","imageUri":"%s"}]' 495642364690.dkr.ecr.us-west-1.amazonaws.com/grigor99:latest > imagedefinitions.json
      - cat imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
    - target/deploy-0.0.1-SNAPSHOT.jar